version: '3.8'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: middleman
    ports:
      - "27017:27017"
    networks:
      - awsvpc

  backend:
    build:
      context: ./src/logic
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - SERVER_IP=localhost
      - MONGO_URI=mongodb://root:root@db:27017/middleman?authSource=admin
    networks:
      - awsvpc

  frontend:
    build:
      context: ./src/view_r
      dockerfile: Dockerfile
      args:
        - REACT_APP_SERVER_IP=localhost
    environment:
      - REACT_APP_SERVER_IP=localhost
    ports:
      - "3000:3000"
    networks:
      - awsvpc

networks:
  awsvpc:
    driver: bridge
